name: extract-branch-variable

on:
  push:
    branches: ['feature/*']

jobs:
  extract-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch
        id: extract_branch
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/feature/}"
      
      - name: Display Branch
        run: echo "${{ steps.extract_branch.outputs.branch }}"
        
      - name: SSH Connect
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd wordpress-boilerplate/
            ## if service exists
            #yq e '.services.web.image = "nginx:1.21-alpine"' -i docker-compose.yml
            ## else
            yq -y --arg featureName "new-workflow" --arg image "nginx:1.21.4-alpine" '
              .services += {
                "feature_\($featureName)":
                {
                  image: $image,
                  networks: ["web"],
                  ports: ["8081:80"],
                  restart: "always"
                }
              }
            ' -i docker-compose.yml
            #docker-compose pull
            #docker-compose up -d