name: extract-branch-variable

on:
  push:
    branches: ['feature/*']

jobs:
  extract-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch
        id: extract_branch
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/feature/}"
      
      - name: Display Branch
        run: echo "${{ steps.extract_branch.outputs.branch }}"
        
      - name: Deploy/Update Feature
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd wordpress-boilerplate/
            ## if service exists
            if ! grep -qR "new-workflow" docker-compose.yml; then
              echo "Feature exists - updating"
              #docker-compose pull
              #docker-compose up -d
            else
              echo "Deploying new feature"
              yq -y --arg featureName "new-workflow" --arg image "nginx:1.21.3-alpine" '
                .services += {
                  "feature_\($featureName)":
                  {
                    image: $image,
                    networks: ["web"],
                    ports: ["8081:80"],
                    restart: "always"
                  }
                }
              ' docker-compose.yml | sponge docker-compose.yml
              #docker-compose pull
              #docker-compose up -d
            fi